apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-os-builder
roleRef:
  kind: ClusterRole
  name: machine-os-builder
subjects:
- kind: ServiceAccount
  namespace: {{.TargetNamespace}}
  name: machine-os-builder
---
# Bind auth-delegator role to the MCC service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-os-builder
  namespace: {{.TargetNamespace}}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  namespace: {{.TargetNamespace}}
  name: machine-os-builder
