apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-os-builder
roleRef:
  kind: ClusterRole
  name: machine-os-builder
subjects:
  - kind: ServiceAccount
    namespace: "{{.TargetNamespace}}"
    name: machine-os-builder
