apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-os-builder-pipelines-scc
roleRef:
  name: "system:openshift:scc:pipelines-scc"
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: machine-os-builder
    kind: ServiceAccount
    namespace: "{{.TargetNamespace}}"
