apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-os-builder
rules:
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineconfigs", "controllerconfigs", "machineconfigpools"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineosconfigs", "machineosconfigs/status", "machineconfigpools/status"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineosbuilds", "machineosbuilds/status"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreamtags"]
  verbs: ["delete"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update"]
