apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-os-builder-configmaps-secrets
  namespace: {{.TargetNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machine-os-builder-configmaps-secrets
subjects:
- kind: ServiceAccount
  namespace: {{.TargetNamespace}}
  name: machine-os-builder
