---
run:
  concurrency: 6
  timeout: 15m
issues:
  exclude-files:
    - ".*_test\\.go"
    - "lib/.*"
cache:
  enabled: true
linters:
  disable-all: true
  enable:
    - depguard
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - canonicalheader
    # - containedctx
    # - contextcheck
    # - copyloopvar
    # - cyclop
    # - decorder
    # - dogsled
    # - dupword
    # - durationcheck
    # - err113
    # - errcheck
    # - errchkjson
    # - errname
    # - errorlint
    # - exhaustive
    # - exhaustruct
    # - fatcontext
    # - forbidigo
    # - forcetypeassert
    # - funlen
    # - gci
    # - ginkgolinter
    # - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gochecksumtype
    # - gocognit
    # - godot
    # - godox
    # - gofumpt
    # - goheader
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - gosmopolitan
    # - grouper
    # - iface
    # - importas
    # - inamedparam
    # - interfacebloat
    # - intrange
    # - ireturn
    # - lll
    # - loggercheck
    # - maintidx
    # - makezero
    # - mirror
    # - mnd
    # - musttag
    # - nakedret
    # - nestif
    # - nilerr
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    # - perfsprint
    # - prealloc
    # - predeclared
    # - promlinter
    # - protogetter
    # - reassign
    # - recvcheck
    # - revive
    # - rowserrcheck
    # - sloglint
    # - spancheck
    # - sqlclosecheck
    # - stylecheck
    # - tagalign
    # - tagliatelle
    # - tenv
    # - testableexamples
    # - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    # - unused
    # - usestdlibvars
    # - varnamelen
    # - wastedassign
    # - whitespace
    # - wrapcheck
    # - wsl
    # - zerologlint
linters-settings:
  gocritic:
    enabled-checks:
      # Diagnostic
      - commentedOutCode
      - nilValReturn
      - octalLiteral
      - sloppyReassign
      - weakCond

      # Performance
      - appendCombine
      - equalFold
      - indexAlloc
      - rangeExprCopy

      # Style
      - boolExprSimplify
      - commentedOutImport
      - docStub
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - methodExprCall
      - stringXbytes
      - typeAssertChain
      - unlabelStmt
      - yodaStyleExpr

      # Opinionated
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock

      # Not used
      # - badLock
      # - badRegexp
      # - badSorting
      # - badSyncOnceFunc
      # - builtinShadow
      # - builtinShadowDecl
      # - deferInLoop
      # - deferUnlambda
      # - dupImport
      # - dynamicFmtString
      # - emptyDecl
      # - evalOrder
      # - exposedSyncMutex
      # - externalErrorReassign
      # - filepathJoin
      # - httpNoBody
      # - hugeParam
      # - importShadow
      # - preferDecodeRune
      # - preferFilepathJoin
      # - preferFprint
      # - preferStringWriter
      # - preferWriteByte
      # - rangeAppendAll
      # - rangeValCopy
      # - redundantSprint
      # - regexpPattern
      # - regexpSimplify
      # - returnAfterHttpError
      # - ruleguard
      # - sliceClear
      # - sortSlice
      # - sprintfQuotedString
      # - sqlQuery
      # - stringConcatSimplify
      # - stringsCompare
      # - syncMapLoadAndDelete
      # - timeExprSimplify
      # - todoCommentWithoutDetail
      # - tooManyResultsChecker
      # - truncateCmp
      # - typeDefFirst
      # - uncheckedInlineErr
      # - unnamedResult
      # - unnecessaryDefer
      # - whyNoLint
  gosec:
    severity: high
    confidence: medium
    excludes:
      - G204
  depguard:
    rules:
      Main:
        deny:
          - desc: "Use k8s.io/klog/v2 instead of github.com/golang/glog"
            pkg: github.com/golang/glog
output:
  formats:
    - format: checkstyle
      path: checkstyle-golangci-lint.xml
    - format: junit-xml
      path: junit-golangci-lint.xml
    - format: colored-line-number
