FROM golang:1.10.3 AS build-env

COPY . /go/src/github.com/openshift/machine-config-operator
WORKDIR /go/src/github.com/openshift/machine-config-operator
RUN WHAT=machine-config-controller ./hack/build-go.sh

FROM scratch
COPY --from=build-env /go/src/github.com/openshift/machine-config-operator/_output/linux/amd64/machine-config-controller /bin/machine-config-controller
COPY templates /etc/templates

ENTRYPOINT ["/bin/machine-config-controller"]
