FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.11 AS builder
WORKDIR /go/src/github.com/openshift/machine-config-operator
COPY . .
RUN WHAT=machine-config-controller ./hack/build-go.sh; \
    mkdir -p /tmp/build; \
    cp /go/src/github.com/openshift/machine-config-operator/_output/linux/$(go env GOARCH)/machine-config-controller /tmp/build/machine-config-controller

FROM registry.svc.ci.openshift.org/ocp/4.0:base
COPY --from=builder /tmp/build/machine-config-controller /usr/bin/
COPY templates /etc/mcc/templates
ENTRYPOINT ["/usr/bin/machine-config-controller"]
