FROM golang:1.10.3 AS build-env

COPY . /go/src/github.com/openshift/machine-config-operator
WORKDIR /go/src/github.com/openshift/machine-config-operator
RUN WHAT=machine-config-server ./hack/build-go.sh

FROM openshift/origin-base:v4.0.0
COPY --from=build-env /go/src/github.com/openshift/machine-config-operator/_output/linux/amd64/machine-config-server /bin/machine-config-server

ENTRYPOINT ["/bin/machine-config-server"]
