FROM golang:1.10.3 AS build-env

COPY . /go/src/github.com/openshift/machine-config-operator
WORKDIR /go/src/github.com/openshift/machine-config-operator
RUN WHAT=machine-config-operator ./hack/build-go.sh

FROM scratch
COPY --from=build-env /go/src/github.com/openshift/machine-config-operator/_output/linux/amd64/machine-config-operator /bin/machine-config-operator
COPY install /manifests

ENTRYPOINT ["/bin/machine-config-operator"]
LABEL io.openshift.release.operator true
