package extended

import (
	"fmt"

	o "github.com/onsi/gomega"
	exutil "github.com/openshift/machine-config-operator/test/extended-priv/util"
	logger "github.com/openshift/machine-config-operator/test/extended-priv/util/logext"
)

// ContainerRuntimeConfig struct is used to handle ContainerRuntimeConfig resources in OCP
type ContainerRuntimeConfig struct {
	Resource
	template string
}

// ContainerRuntimeConfigList handles list of nodes
type ContainerRuntimeConfigList struct {
	ResourceList
}

// NewContainerRuntimeConfig creates a ContainerRuntimeConfig struct
func NewContainerRuntimeConfig(oc *exutil.CLI, name, template string) *ContainerRuntimeConfig {
	return &ContainerRuntimeConfig{Resource: *NewResource(oc, "ContainerRuntimeConfig", name), template: template}
}

// NewContainerRuntimeConfigList create a NewKubeletConfigList struct
func NewContainerRuntimeConfigList(oc *exutil.CLI) *ContainerRuntimeConfigList {
	return &ContainerRuntimeConfigList{*NewResourceList(oc, "ContainerRuntimeConfig")}
}

// TODO: Refactor this strutc remove this method and embed Template
func (cr *ContainerRuntimeConfig) create(parameters ...string) {
	allParams := []string{"--ignore-unknown-parameters=true", "-f", cr.template,
		"-p", "NAME=" + cr.name}
	allParams = append(allParams, parameters...)
	exutil.CreateClusterResourceFromTemplate(cr.oc, allParams...)
}

func (cr ContainerRuntimeConfig) waitUntilSuccess(timeout string) {
	logger.Infof("wait for %s to report success", cr.name)
	o.EventuallyWithOffset(1, &cr, timeout, "2s").Should(o.SatisfyAll(
		HaveConditionField("Success", "status", "True"),
		HaveConditionField("Success", "message", "Success"),
	))
}

func (cr ContainerRuntimeConfig) waitUntilFailure(expectedMsg, timeout string) {
	logger.Infof("wait for %s to report failure", cr.name)
	o.EventuallyWithOffset(1, &cr, timeout, "2s").Should(o.SatisfyAll(
		HaveConditionField("Failure", "status", "False"),
		HaveConditionField("Failure", "message", o.ContainSubstring(expectedMsg)),
	))
}

// GetGeneratedMCName returns the name of the MC that was generated by this ContainerRuntimeConfig resource
func (cr ContainerRuntimeConfig) GetGeneratedMCName() (string, error) {
	mcName, err := cr.Get(`{.metadata.finalizers[0]}`)
	if err != nil {
		return "", err
	}
	if mcName == "" {
		return "", fmt.Errorf("It was not possible to get the finalizer from %s %s: %s", cr.GetKind(), cr.GetName(), cr.PrettyString())
	}
	return mcName, nil
}

// GetGeneratedMCName returns the name of the MC that was generated by this ContainerRuntimeConfig resource and fails the test case if it cannot be done
func (cr ContainerRuntimeConfig) GetGeneratedMCNameOrFail() string {
	mcName, err := cr.GetGeneratedMCName()
	o.Expect(err).NotTo(o.HaveOccurred(), "Error getting the generated MC for %s %s", cr.GetKind(), cr.GetName())
	return mcName
}
