package common

const (
	// MCONamespace is the namespace that should be used for all API objects owned by the MCO by default
	MCONamespace = "openshift-machine-config-operator"

	// GeneratedByControllerVersionAnnotationKey is used to tag the machineconfigs generated by the controller with the version of the controller.
	GeneratedByControllerVersionAnnotationKey = "machineconfiguration.openshift.io/generated-by-controller-version"

	// ReleaseImageVersionAnnotationKey is used to tag the rendered machineconfigs & controller config with the release image version.
	ReleaseImageVersionAnnotationKey = "machineconfiguration.openshift.io/release-image-version"

	// OSImageURLOverriddenKey is used to tag a rendered machineconfig when OSImageURL has been overridden from default using machineconfig
	OSImageURLOverriddenKey = "machineconfiguration.openshift.io/os-image-url-overridden"

	// ControllerConfigName is the name of the ControllerConfig object that controllers use
	ControllerConfigName = "machine-config-controller"

	// KernelTypeDefault denominates the default kernel type
	KernelTypeDefault = "default"

	// KernelTypeRealtime denominates the realtime kernel type
	KernelTypeRealtime = "realtime"

	// MasterLabel defines the label associated with master node. The master taint uses the same label as taint's key
	MasterLabel = "node-role.kubernetes.io/master"

	// MCNameSuffixAnnotationKey is used to keep track of the machine config name associated with a CR
	MCNameSuffixAnnotationKey = "machineconfiguration.openshift.io/mc-name-suffix"

	// MaxMCNameSuffix is the maximum value of the name suffix of the machine config associated with kubeletconfig and containerruntime objects
	MaxMCNameSuffix int = 9

	// ClusterFeatureInstanceName is a singleton name for featureGate configuration
	ClusterFeatureInstanceName = "cluster"

	// ClusterNodeInstanceName is a singleton name for node configuration
	ClusterNodeInstanceName = "cluster"

	// MachineConfigPoolMaster is the MachineConfigPool name given to the master
	MachineConfigPoolMaster = "master"

	// MachineConfigPoolWorker is the MachineConfigPool name given to the worker
	MachineConfigPoolWorker = "worker"

	// LayeringEnabledPoolLabel is the label that enables the "layered" workflow path for a pool.
	LayeringEnabledPoolLabel = "machineconfiguration.openshift.io/layering-enabled"

	// ExperimentalLayeringPoolLabel is the label that enables the "layered" workflow path for a pool
	ExperimentalLayeringPoolLabel = "machineconfiguration.openshift.io/layered"

	// ExperimentalLayeringPoolImageStreamLabel is the label that enables tells the pool which imagestream to grab images out of
	ExperimentalLayeringPoolImageStreamLabel = "machineconfiguration.openshift.io/selected-image-stream"

	// ExperimentalNewestLayeredImageAnnotationKey is the annotation that signifies the newest image that has been pushed to a machine
	// config pool's imagestream
	ExperimentalNewestLayeredImageAnnotationKey = "machineconfiguration.openshift.io/newestImage"
	// ExperimentalNewestLayeredImageEquivalentConfigAnnotationKey is the annotation that signifies which rendered config
	// the latest image in the pool's imagestream is equivalent to
	ExperimentalNewestLayeredImageEquivalentConfigAnnotationKey = "machineconfiguration.openshift.io/newestImageEquivalentConfig"

	// CoreOSImageStreamName is the name of the global (non-pool-specific) default base image stream name that pools will draw from if they
	// do not have any other base image specified
	CoreOSImageStreamName = "coreos"

	// ImageStreamSuffixCoreOS is the suffix for the imagestream holding the base coreos image
	ImageStreamSuffixCoreOS = "-base"
	// ImageStreamSuffixExternalBase is the suffix for a pool imagestream  where the base image comes from outside the cluster
	ImageStreamSuffixExternalBase = "-external-base"

	// ImageStreamSuffixRenderedConfig is the suffix for a pool imagestream where the mco also writes its rendered machineconfig
	ImageStreamSuffixRenderedConfig = "-rendered-config"
	// ImageStreamSuffixMCOContent  is the suffix for a pool imagestream where the mco has applied its rendered-config to the base image
	ImageStreamSuffixMCOContent = "-mco-content"
	// ImageStreamSuffixMcoContentCustom is the suffix for a pool imagestream where content has been customized by a user
	ImageStreamSuffixMCOContentCustom = "-mco-content-custom"
	// ImageStreamSuffixMCOContentExternal is the suffix for a pool imagestream  where content comes from outside the cluster
	ImageStreamSuffixMCOContentExternal = "-mco-content-external"

	// ImageStreamSuffixMCOContentPerNode is the suffix for a pool imagestream containing any per-node images
	ImageStreamSuffixMCOContentPerNode = "-mco-content-per-node"
)
