---
kind: Pod
apiVersion: v1
metadata:
  name: kube-vip-api
  namespace: openshift-kube-vip
  labels:
    app: kube-vip
    component: api
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: Exists
  containers:
  - name: kube-vip
    image: {{ .Images.KubeVIPBootstrap }}
    args:
    - manager
    env:
    - name: address
      value: "{{ onPremPlatformAPIServerInternalIP .ControllerConfig }}"
    - name: k8s_config_file
      value: "/etc/kubernetes/kubeconfig"
    - name: kubernetes_addr
      value: "https://localhost:6443"
    - name: port
      value: "6443"
    - name: cp_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_routingtable
      value: "true"
    - name: vip_cleanroutingtable
      value: "true"
    - name: vip_routingtableid
      value: "198"
    - name: vip_routingtableprotocol
      value: "248"
    - name: backend_health_check_interval
      value: "5"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - name: kubeconfig
      mountPath: /etc/kubernetes
      readOnly: true
  volumes:
  - name: kubeconfig
    hostPath:
      path: /etc/kubernetes
