apiVersion: machineconfiguration.openshift.io/v1
kind: MachineState
metadata:
  name: mcc-health
  labels:
    "states.operator.machineconfiguration.openshift.io/mcc": ""
spec:
  machineStateKind: ControllerState