#!/bin/sh

podman build \
	--tag=localhost/machine-config-operator:latest \
	--label=io.openshift.build.commitauthor= \
	--label=io.openshift.build.commitdate \
	--label=io.openshift.build.commitid \
	--label=io.openshift.build.commitmessage \
	--label=io.openshift.build.commitref \
	--label=vcs-ref=$(git rev-parse HEAD) \
	--label=vcs-type=git \
	--label=vcs-url= \
	.
