#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_ROOT=$(dirname ${BASH_SOURCE})/..

kubelet_yaml_path() {
    local role=$1
    local type=$2
    echo $SCRIPT_ROOT/templates/$role/01-$role-kubelet/$type/units/kubelet.service.yaml
}

logpath() {
    realpath --relative-to="$SCRIPT_ROOT" "$1"
}

gen_worker_kubelet_service() {
    local type=$1
    local master=$(kubelet_yaml_path master $type)
    local worker=$(kubelet_yaml_path worker $type)
    echo "Generating template $(logpath $worker) from $(logpath $master)"
    echo "# Autogenerated from $(logpath $master) via hack/update-templates.sh; do not edit" > "$worker"
    sed 's:--node-labels=node-role.kubernetes.io/control-plane,node-role.kubernetes.io/master:--node-labels=node-role.kubernetes.io/worker:
         /--register-with-taints=node-role.kubernetes.io\/master=:NoSchedule/d' "$master" >>"$worker"
}

gen_worker_kubelet_service _base
gen_worker_kubelet_service on-prem
gen_worker_kubelet_service alibabacloud

