filesystem: "root"
mode: 0644
path: "/etc/kubernetes/static-pod-resources/mdns/config.hcl.tmpl"
contents:
  inline: |
    bind_address = "{{`{{ .NonVirtualIP }}`}}"
    collision_avoidance = "hostname"

    service {
        name = "{{`{{ .Cluster.Name }}`}} Workstation"
        host_name = "{{`{{ .ShortHostname }}`}}.local."
        type = "_workstation._tcp"
        domain = "local."
        port = 42424
        ttl = 3200
    }
