# Network policy for the machine-config-operator pod.
#
# Egress:
# - Allow all egress to support communication with the Kubernetes API server,
#   whose IP address and port are not known at manifest time. This implicitly
#   covers DNS resolution as well.
#
# Ingress:
# - Allow ingress on port 9001 (metrics) so that Prometheus can scrape metrics.
#   The metrics endpoint uses kube-rbac-proxy for authentication.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-machine-config-operator
  namespace: {{.TargetNamespace}}
spec:
  podSelector:
    matchLabels:
      k8s-app: machine-config-operator
  ingress:
  - ports:
    - protocol: TCP
      port: 9001
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
