apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-machine-config-controller
  namespace: {{.TargetNamespace}}
spec:
  podSelector:
    matchLabels:
      k8s-app: machine-config-controller
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-monitoring
    ports:
    - protocol: TCP
      port: 9001
  egress:
  - to:
    ports:
    - protocol: TCP
      port: 6443
  - to:
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
