apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-machine-os-builder
  namespace: {{.TargetNamespace}}
spec:
  podSelector:
    matchLabels:
      k8s-app: machine-os-builder
  policyTypes:
  - Egress
  egress:
  - {}
