package internalreleaseimage

import (
	mcfgv1 "github.com/openshift/api/machineconfiguration/v1"
)

// RunInternalReleaseImageBootstrap generates a MachineConfig object for InternalReleaseImage that would have been generated by syncInternalReleaseImage
func RunInternalReleaseImageBootstrap(controllerConfig *mcfgv1.ControllerConfig) ([]*mcfgv1.MachineConfig, error) {
	return generateInternalReleaseImageMachineConfig(controllerConfig)
}
