package internalreleaseimage

import (
	corev1 "k8s.io/api/core/v1"

	mcfgv1 "github.com/openshift/api/machineconfiguration/v1"
	mcfgv1alpha1 "github.com/openshift/api/machineconfiguration/v1alpha1"
)

// RunInternalReleaseImageBootstrap generates the MachineConfig objects for InternalReleaseImage that would have been generated by syncInternalReleaseImage.
func RunInternalReleaseImageBootstrap(iri *mcfgv1alpha1.InternalReleaseImage, iriSecret *corev1.Secret, cconfig *mcfgv1.ControllerConfig) ([]*mcfgv1.MachineConfig, error) {
	configs := []*mcfgv1.MachineConfig{}

	for _, role := range SupportedRoles {
		r := NewRendererByRole(role, iri, iriSecret, cconfig)
		mc, err := r.CreateEmptyMachineConfig()
		if err != nil {
			return nil, err
		}
		err = r.RenderAndSetIgnition(mc)
		if err != nil {
			return nil, err
		}
		configs = append(configs, mc)
	}

	return configs, nil
}
