mode: 0755
path: "/usr/local/bin/configure-ip-forwarding.sh"
contents:
  inline: |
    #!/bin/bash
    set -ex

    # Used for on-prem deployments to enable ip forwarding as part of nodeip-configuration service.
    # IP forwarding is required on the node IP (k8s API) interface in order for keepalived to function.

    echo "Configuring IP Forwarding..."
    ovnk_config_dir='/etc/ovnk'
    ip_hint_file="/run/nodeip-configuration/primary-ip"

    get_ip_from_ip_hint_file() {
      local ip_hint_file="$1"
      if [[ ! -f "${ip_hint_file}" ]]; then
        echo "error: unable to enable IP forwarding. IP hint file: ${ip_hint_file} does not exist!"
        exit 1
      fi
      ip_hint=$(cat "${ip_hint_file}")
      echo "${ip_hint}"
    }

    get_nodeip_hint_interface() {
      local ip_hint=""
      local ip_hint_file="$1"
      local iface=""

      ip_hint=$(get_ip_from_ip_hint_file "${ip_hint_file}")
      if [[ -z "${ip_hint}"  ]]; then
        echo "error: unable to enable IP forwarding. IP hint file: ${ip_hint_file} is empty!"
        exit 1
      fi

      iface=$(ip -j addr | jq -r "first(.[] | select(any(.addr_info[]; .local==\"${ip_hint}\"))) | .ifname")
      if [[ -z "${iface}" ]]; then
        echo "error: unable to enable IP forwarding. Cannot detect valid interface within file: ${ip_hint_file}"
        exit 1
      fi
      echo "${iface}"
    }

    iface=$(get_nodeip_hint_interface "${ip_hint_file}")

    echo "Node IP interface determined as: ${iface}. Enabling IP forwarding..."
    echo "1" > /proc/sys/net/ipv4/conf/"${iface}"/forwarding
    echo "1" > /proc/sys/net/ipv6/conf/"${iface}"/forwarding
