mode: 0755
path: "/etc/kubernetes/static-pod-resources/keepalived/scripts/chk_default_ingress.sh.tmpl"
contents:
  inline: |
    #!/bin/bash
    /host/bin/crictl -r unix:///host/run/crio/crio.sock pods --namespace openshift-ingress --state Ready | grep -q 'router-default-[[:xdigit:]]\{10\}-[[:alnum:]]\{5\}'
