mode: 0755
path: "/etc/kubernetes/static-pod-resources/frr/scripts/chk_ocp_script_ingress.sh.tmpl"
contents:
  inline: |
    #!/bin/bash
    /usr/bin/curl -o /dev/null -kLfs https://localhost:{{`{{ .LBConfig.LbPort }}`}}/readyz
