apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-config-operator-vsphere
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: vsphere-cloud-credentials
    namespace: openshift-machine-config-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: VSphereProviderSpec
