apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-quorum-guard
  namespace: openshift-machine-config-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: etcd-quorum-guard
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: etcd-quorum-guard
        k8s-app: etcd-quorum-guard
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - "etcd-quorum-guard"
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      terminationGracePeriodSeconds: 3
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 120
      - key: node-role.kubernetes.io/etcd
        operator: Exists
        effect: NoSchedule
      containers:
      - image: quay.io/openshift/origin-cli:latest
        imagePullPolicy: IfNotPresent
        name: guard
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /mnt/kube
          name: kubecerts
        command:
        - /bin/bash
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        args:
        - -c
        - |
          # properly handle TERM and exit as soon as it is signaled
          set -euo pipefail
          trap 'jobs -p | xargs -r kill; exit 0' TERM
          # prepare readiness script
          declare -r croot=/mnt/kube
          declare -r health_endpoint="https://${NODE_IP}:2379/health"
          declare -r cert="${croot}/system:etcd-peer-${NODE_NAME}.crt"
          declare -r key="${croot}/system:etcd-peer-${NODE_NAME}.key"
          declare -r cacert="$croot/ca.crt"
          export NSS_SDB_USE_CACHE=no
          [[ -z $cert || -z $key ]] && exit 1
          echo "curl --silent --max-time 2 --cert \"${cert//:/\:}\" --key \"$key\" --cacert \"$cacert\" \"$health_endpoint\"" > /usr/local/bin/etcd-quorum-guard.sh

          chmod +x /usr/local/bin/etcd-quorum-guard.sh
          sleep infinity & wait
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /usr/local/bin/etcd-quorum-guard.sh
            initialDelaySecond: 5
            periodSecond: 5
        resources:
          requests:
            cpu: 10m
            memory: 5Mi
        securityContext:
          privileged: true
      volumes:
      - name: kubecerts
        hostPath:
          path: /etc/kubernetes/static-pod-resources/etcd-member
