apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-config-osimageurl
  namespace: openshift-machine-config-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
data:
  releaseVersion: 0.0.1-snapshot
  baseOSContainerImage: "placeholder.url.oc.will.replace.this.org/placeholdernamespace:rhel-coreos"
  baseOSExtensionsContainerImage: "placeholder.url.oc.will.replace.this.org/placeholdernamespace:rhel-coreos-extensions"
  osImageURL: ""
  streams.json: >
    {
      "default": "rhel-coreos",
      "streams": {
        "rhel-coreos": {
          "baseOSContainerImage": "placeholder.url.oc.will.replace.this.org/placeholdernamespace:rhel-coreos",
          "baseOSExtensionsContainerImage": "placeholder.url.oc.will.replace.this.org/placeholdernamespace:rhel-coreos-extensions"
        }
      }
    }
