apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: crio-tls
  labels:
    app.kubernetes.io/name: kube-rbac-proxy
    app.kubernetes.io/version: v0.4.1
  name: crio
  namespace: openshift-node
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9999
    targetPort: https
  selector:
    app.kubernetes.io/name: kube-rbac-proxy
    app.kubernetes.io/version: v0.4.1
