allowHostNetwork: true
allowHostPorts: true
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: crio scc is used for securing cri-o metrics endpoint
  name: crio
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users: []
