kind: ConfigMap
apiVersion: v1
metadata:
  name: ignore-major_version-manifest
  namespace: default
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/major-version: "4"
data:
  key: "new-implementation"