#!/bin/bash
set -xeuo pipefail
# Gather debugging stuff; this might be better in our Prow job
# down the line.
oc get nodes
for item in machineconfigpool machineconfigs ds pods; do
    oc -n openshift-machine-config-operator get ${item}
done
for item in operator controller; do
    oc -n openshift-machine-config-operator logs deploy/machine-config-${item}
done
