apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-config-controller-configmaps
  namespace: openshift-config-managed
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update"]
