apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "osimagestream-prevent-deletion-binding"
spec:
  policyName: "osimagestream-prevent-deletion"
  validationActions: [Deny]
