mode: 0755
path: "/usr/local/bin/nmstate-configuration.sh"
contents:
  inline: |
    #!/bin/bash
    set -eux

    # Clean up old config on behalf of mtu-migration
    if ! systemctl -q is-enabled mtu-migration; then
      echo "Cleaning up left over mtu migration configuration"
      rm -rf /etc/cno/mtu-migration
    fi

    src_path="/etc/nmstate/openshift"
    dst_path="/etc/nmstate"
    hostname=$(hostname -s)
    host_file="${hostname}.yml"
    cluster_file="cluster.yml"
    config_file=""
    if [ -s "$src_path/$host_file" ]; then
      config_file=$host_file
    elif [ -s "$src_path/$cluster_file" ]; then
      config_file=$cluster_file
    else
      echo "No configuration found at $src_path/$host_file or $src_path/$cluster_file"
      exit 0
    fi
    
    if [ -e "$src_path/applied" ]; then
      sha_applied=$(sha256sum "$src_path/applied" | awk '{print $1}')
      sha_config=$(sha256sum "$src_path/$config_file" | awk '{print $1}')
      if ["$sha_applied"=="$sha_config"]; then
        echo "Configuration already applied, exiting"
        exit 0
      fi
    fi

    if [ -e "$dst_path/$config_file" ]; then
      echo "ERROR: File $dst_path/$config_file exists. Refusing to overwrite."
      exit 1
    fi

    cp "$src_path/$config_file" /etc/nmstate
    cp "$src_path/$config_file" "$src_path/applied"
